module.exports = [
	"Life is a series of interconnected moments, each one shaping the narrative of our existence. In the hustle and bustle of our daily routines, it's easy to overlook the beauty of these moments. Take a step back and think about a time when you felt truly alive, fully present in the here and now. What were you doing, and what made that moment so special?",
	"The natural world is a masterpiece of design and complexity. Whether it's the intricate patterns of a snowflake or the delicate dance of a butterfly, there's a profound sense of wonder that nature evokes. Share an experience where you felt a deep connection with the natural world, and how it made you appreciate the beauty of our planet.",
	'Stories have the power to transport us to different times and places, allowing us to experience the lives of others. Literature, in particular, has a unique way of connecting us with the human experience. Can you recall a book that resonated with you on a profound level, one that made you see the world in a different light?',
	"In the tapestry of life, adversity is a thread that weaves through every person's story. It's in our struggles and challenges that we discover our true strength and resilience. Share a personal experience where you faced adversity, overcame it, and emerged as a stronger, wiser individual.",
	"The night sky, adorned with a multitude of stars, is a reminder of the vastness and mystery of the universe. It's a canvas that has inspired countless myths, stories, and scientific discoveries. Have you ever stargazed in a remote location, far from city lights, and felt a profound connection with the cosmos? What was that experience like?",
	"Our world is filled with cultural diversity, and it's in the richness of these cultures that we find a tapestry of traditions, art, and customs. Is there a specific cultural celebration or tradition that you find particularly fascinating or meaningful? What about it resonates with you?",
	"Time has a way of shaping us, molding us into the individuals we become. Looking back on your life's journey, can you identify a specific moment or period that you believe had the most significant influence on who you are today? What lessons did you learn from that experience?",
	'The ocean is a realm of mystery, covering more than 70% of our planet. Its depths hold uncharted territories and creatures we have yet to discover. Have you ever had the opportunity to explore the ocean, either through scuba diving, snorkeling, or sailing? What did you find most captivating about your underwater adventure?',
	"Kindness is a universal language that transcends cultural boundaries. It has the power to brighten someone's day and create a ripple effect of positivity. Share a story about a random act of kindness you've witnessed or been a part of, and how it left a lasting impact on those involved.",
	'Friendship is a treasure that enriches our lives. Think about a moment when a friend stood by your side during a difficult time, offering support and understanding. How did their friendship make a difference in your life, and what did you learn from that experience?',
];
